PACKAGE     := $(shell basename `dirname \`pwd\``)Func
LIB_TYPE    := shared
LIB         := lib$(PACKAGE)
LIBCXXFILES := $(wildcard *.cxx)

include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_art.mk
